name: Docs
on: [push, pull_request, workflow_dispatch]
permissions:
    contents: write
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install dependencies
        run: |
          pip install sphinx sphinx_rtd_theme sphinx-copybutton pydata-sphinx-theme
      - name: Sphinx build
        run: |
          sphinx-build -a -b html doc/source _build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GH_PAGE_ACTION_TOKEN }}
          publish_dir: _build/
          force_orphan: true
          cname: www.wanniertools.com
